### ISSUE TITLE
link to download moved?

### ISSUE THREAD

**Issue by tomgreenwood1** [CAIDA/libbgpstream#145]
Apologies if I am being dumb, but if I try to download the source code like this

`curl -v http://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/libbgpstream-2.0.0-beta-6.tar.gz`

I get this result:

```
* About to connect() to bgpstream.caida.org port 80 (#0)
*   Trying 192.172.226.51...
* Connected to bgpstream.caida.org (192.172.226.51) port 80 (#0)
> GET /bundles/caidabgpstreamwebhomepage/dists/libbgpstream-2.0.0-beta-6.tar.gz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: bgpstream.caida.org
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 29 Jul 2019 16:17:55 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/libbgpstream-2.0.0-beta-6.tar.gz
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host bgpstream.caida.org left intact
```

has the location moved?

Thanks

Tom

**Comment by digizeph** [comment]
Hey Tom, thank you contacting us on this matter. We host all links with HTTPS now. The problem you encounter was curl hit the redirection to the corresponding https url.
You should be able to download it using the following command:
`curl -LOv curl -v http://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/libbgpstream-2.0.0-beta-6.tar.gz`
`-L` allows curl to follow the redirection, and `-O` makes it download the file directly rather than dumping the content to stdout.

Also, beta-7 is available now, I suggest you use that instead. 
Cheers!

**Comment by tomgreenwood1** [comment]
Thanks so much for the quick response Mingwei. That makes perfect sense.

**Comment by digizeph** [comment]
You are welcome! I will close this issue now. Feel free to contact us if you encountered any problems.
